title: 飞虎兄的博客
author: Brandon
email: jifeihu@foxmail.com
description: 飞虎兄的博客
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
sass:
  sass_dir: _sass
plainwhite:
  name: 飞虎兄
  tagline: Developer
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content

  # generate social links in footer
  social_links:
    github:  brandonbai
    linkedIn: in/飞虎-冀-316316171
    weibo: ygcdjfh
    rss: rss

header_pages:
- about.md

# Build settings
# theme: plainwhite
remote_theme: thelehhman/plainwhite-jekyll

